### 服务器配置
server:
  port: 8077


### spring配置
spring:
  ## 数据库配置
  datasource:
    # 下面为连接池的补充设置，应用到上面所有数据源中
    druid:
      #primary是主要连接池,要加其他自行加
      primary:
       name: gtmcandon
       url: jdbc:sqlserver://101.200.127.27:1433;databaseName=tool_manage
       username: sa
       password: 123456ASD!

       driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver   #com.microsoft.sqlserver.jdbc.SQLServerDriver  com.mysql.cj.jdbc.Driver
          # 使用druid数据源
       platform: mysql
       type: com.alibaba.druid.pool.DruidDataSource
      # 初始化大小，最小，最大
       initialSize: 50
       minIdle: 500
       maxActive: 2000
      # 配置获取连接等待超时的时间
       maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
       timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
       minEvictableIdleTimeMillis: 30000
       validationQuery: SELECT 1
       testWhileIdle: true
       testOnBorrow: false
       testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
       poolPreparedStatements: true
       maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
       filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
       connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true

  ## jpa配置
  jpa:
    show-sql: true #多数据源下要指定数据源才能起效
    hibernate:
      ddl-auto: create  #多数据源下要指定数据源才能起效
      primary-dialect: org.hibernate.dialect.SQLServer2008Dialect
      ##hibernate.second-dialect: org.hibernate.dialect.MySQL5Dialect
      #hibernate.format_sql: false
    #open-in-view: true

